# Makefile for COMP1521 Lab06

CC=dcc
#CC=gcc
CFLAGS=-Wall -Werror
LDFLAGS=-lbsd
#LDFLAGS=

#all : myls stat
all : mylsChal stat

#myls : myls.c
mylsCopy : mylsChal.c

stat : stat.c

clean:
	rm -f myls stat *.o core
